<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\AboutServices\**" />
    <Compile Remove="Services\BrandServices\**" />
    <Compile Remove="Services\GetInTouchServices\**" />
    <Compile Remove="Services\HowItWorkServices\**" />
    <Compile Remove="Services\OfferServices\**" />
    <Compile Remove="Services\ProjectSectionServices\**" />
    <Compile Remove="Services\QuestionServices\**" />
    <Compile Remove="Services\ShipmentServices\**" />
    <Compile Remove="Services\ShipmentTrackingServices\**" />
    <Compile Remove="Services\TestimonialServices\**" />
    <Content Remove="Services\AboutServices\**" />
    <Content Remove="Services\BrandServices\**" />
    <Content Remove="Services\GetInTouchServices\**" />
    <Content Remove="Services\HowItWorkServices\**" />
    <Content Remove="Services\OfferServices\**" />
    <Content Remove="Services\ProjectSectionServices\**" />
    <Content Remove="Services\QuestionServices\**" />
    <Content Remove="Services\ShipmentServices\**" />
    <Content Remove="Services\ShipmentTrackingServices\**" />
    <Content Remove="Services\TestimonialServices\**" />
    <EmbeddedResource Remove="Services\AboutServices\**" />
    <EmbeddedResource Remove="Services\BrandServices\**" />
    <EmbeddedResource Remove="Services\GetInTouchServices\**" />
    <EmbeddedResource Remove="Services\HowItWorkServices\**" />
    <EmbeddedResource Remove="Services\OfferServices\**" />
    <EmbeddedResource Remove="Services\ProjectSectionServices\**" />
    <EmbeddedResource Remove="Services\QuestionServices\**" />
    <EmbeddedResource Remove="Services\ShipmentServices\**" />
    <EmbeddedResource Remove="Services\ShipmentTrackingServices\**" />
    <EmbeddedResource Remove="Services\TestimonialServices\**" />
    <None Remove="Services\AboutServices\**" />
    <None Remove="Services\BrandServices\**" />
    <None Remove="Services\GetInTouchServices\**" />
    <None Remove="Services\HowItWorkServices\**" />
    <None Remove="Services\OfferServices\**" />
    <None Remove="Services\ProjectSectionServices\**" />
    <None Remove="Services\QuestionServices\**" />
    <None Remove="Services\ShipmentServices\**" />
    <None Remove="Services\ShipmentTrackingServices\**" />
    <None Remove="Services\TestimonialServices\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="MongoDB.Bson" Version="3.6.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.6.0" />
    <PackageReference Include="MongoDB.Driver.Core" Version="2.30.0" />
  </ItemGroup>

</Project>
